### ISSUE TITLE
佛布朗斯基请求添加友链

### ISSUE THREAD

**Issue by FBLMG** [liangguifeng/liangguifeng.github.io#1]
本站名称：佛布朗斯基
本站链接：https://hongzx.cn
本站描述：https://hongzx.cn/fblsj.png
本站图标：关于PHP与服务器相关技术分享～

**Comment by liangguifeng** [comment]
> 本站名称：佛布朗斯基 本站链接：https://hongzx.cn站点 描述：https://hongzx.cn/fblsj.png 本站图标：关于PHP与服务器相关技术分享～

已添加
